language: node_js
node_js:
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: aa9c5a975b54de7484c4b4270bc23020cc31b5b052a9c54111e4bd454dd9ff17
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info